language: ruby
rvm:
  - 2.3.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS inventory_ci_staging;'
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml